# ci.yml
# - 역할: 트리거 정의
# - 언제 실행할지만 담당

# reusable-ci.yml
# - 역할: job 묶음
# - 여러 job -> 한 줄 uses:

# action.yml
# - step 묶음
# - 여러 step -> 한 줄 uses:

# 워크플로우 이름
name: CI

# 트리거 - 언제 실행할 지
on:
  pull_request:
    branches:
      - main

# jobs 선언 + job 이름
jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: "3.12"
    secrets: inherit # GITHUB_TOKEN을 비록한 secrets는 호출자 ci.yml 컨텍스트에 있음. reusable workflow는 별도 컨텍스트에서 실행되므로 Inherit을 붙여야 PR 코멘트 작성 등에서 GITHUB_TOKEN을 쓸 수 있음.
    permissions:
      contents: read
      pull-requests: write
